apiVersion: batch/v1
kind: Job
metadata:
  name: download-taide-llama8b-model
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: hf-downloader
        image: registry.access.redhat.com/ubi9/python-312:latest
        command:
          - /bin/bash
          - -c
          - |
            pip install --no-cache-dir huggingface_hub
            mkdir -p /mnt/models/taide/Gemma-3-TAIDE-12b-Chat
            hf download \
              taide/Llama-3.1-TAIDE-LX-8B-Chat \
              --local-dir /mnt/models/ \
              --token 'hf_xxxxxx'
        volumeMounts:
          - name: model-storage
            mountPath: /mnt/models
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: vllm-model-pvc
